### PR TITLE
task/24/landing

### PR DESCRIPTION
**Pull request by al6862**
lol sorry its just a copy of the homepage feed

was gonna also add in this branch the stuff to check if the user is not authorized, so we know when the path "/" is the landing feed or homepage feed, but its getting kind of complicated so i decided to move it to its own separate branch

### CODE REVIEW

**Comment by Silver1793** [comment]
> lol sorry its just a copy of the homepage feed
> 
> was gonna also add in this branch the stuff to check if the user is not authorized, so we know when the path "/" is the landing feed or homepage feed, but its getting kind of complicated so i decided to move it to its own separate branch

Why do we need a copy of the homepage feed?

**Comment by al6862** [comment]
Hmmm eventually we need a landing feed for nonauthorized users that's different from the home feed for authorized users? Right now from what I understand from our wireframes, both feeds are pretty much the same since we don't have backend to determine which reviews are posted on the landing feed versus the home feed

**Comment by al6862** [comment]
In the other pr for notauthnav, i also added a <h1> Welcome to Music Ranking App </h1> to easily differentiate the two though

**Comment by Silver1793** [comment]
> Hmmm eventually we need a landing feed for nonauthorized users that's different from the home feed for authorized users? Right now from what I understand from our wireframes, both feeds are pretty much the same since we don't have backend to determine which reviews are posted on the landing feed versus the home feed

Sorry just for clarification, what can authorized people see/do/go to and what can unauthorized ppl see/do/go to? I think we can use the same page for both but I want to make sure i understand the differences first.

**Comment by al6862** [comment]
this is what i put in app.js in the notauthnav pr:

image

so i just assumed that unauthorized users cant go to Settings, Profile Review (aka My Profile?), and the Homepage Feed; unauthorized users also see the NotAuthNav instead of the Nav

i definitely agree that we should prob discuss more about what not logged in people can do though

**Pull request closed without merging**
